// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: packetToProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.CrapCord.PacketToProto {

  /// <summary>Holder for reflection information generated from packetToProto.proto</summary>
  public static partial class PacketToProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for packetToProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketToProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwYWNrZXRUb1Byb3RvLnByb3RvEgtwYWNrZXRwcm90byKqAgoLUGFja2V0",
            "UHJvdG8SNQoGT3Bjb2RlGAEgASgOMiUucGFja2V0cHJvdG8uUGFja2V0UHJv",
            "dG8uUGFja2V0T3Bjb2RlEhEKCVRpbWVzdGFtcBgCIAEoCRIPCgdQYXlsb2Fk",
            "GAMgASgJEgwKBEhNQUMYBCABKAkisQEKDFBhY2tldE9wY29kZRIMCghSZWdp",
            "c3RlchAAEgkKBUxvZ2luEAESDQoJVmlld1Jvb21zEAISEQoNRmV0Y2hNZXNz",
            "YWdlcxADEg8KC1NlbmRNZXNzYWdlEAQSDgoKQ3JlYXRlUm9vbRAFEgwKCEpv",
            "aW5Sb29tEAYSDAoIUmVzcG9uc2UQBxIOCgpLZXlIYW5kb2ZmEAgSCAoEQXV0",
            "aBAJEg8KCkRpc2Nvbm5lY3QQ/wFCKaoCJkdvb2dsZS5Qcm90b2J1Zi5DcmFw",
            "Q29yZC5QYWNrZXRUb1Byb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.CrapCord.PacketToProto.PacketProto), global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Parser, new[]{ "Opcode", "Timestamp", "Payload", "HMAC" }, null, new[]{ typeof(global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PacketProto : pb::IMessage<PacketProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PacketProto> _parser = new pb::MessageParser<PacketProto>(() => new PacketProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PacketProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.CrapCord.PacketToProto.PacketToProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketProto(PacketProto other) : this() {
      opcode_ = other.opcode_;
      timestamp_ = other.timestamp_;
      payload_ = other.payload_;
      hMAC_ = other.hMAC_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PacketProto Clone() {
      return new PacketProto(this);
    }

    /// <summary>Field number for the "Opcode" field.</summary>
    public const int OpcodeFieldNumber = 1;
    private global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode opcode_ = global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode Opcode {
      get { return opcode_; }
      set {
        opcode_ = value;
      }
    }

    /// <summary>Field number for the "Timestamp" field.</summary>
    public const int TimestampFieldNumber = 2;
    private string timestamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private string payload_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HMAC" field.</summary>
    public const int HMACFieldNumber = 4;
    private string hMAC_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HMAC {
      get { return hMAC_; }
      set {
        hMAC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PacketProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PacketProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Opcode != other.Opcode) return false;
      if (Timestamp != other.Timestamp) return false;
      if (Payload != other.Payload) return false;
      if (HMAC != other.HMAC) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Opcode != global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register) hash ^= Opcode.GetHashCode();
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (HMAC.Length != 0) hash ^= HMAC.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Opcode != global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Opcode);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Timestamp);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Payload);
      }
      if (HMAC.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HMAC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Opcode != global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Opcode);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Timestamp);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Payload);
      }
      if (HMAC.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HMAC);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Opcode != global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Opcode);
      }
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Payload);
      }
      if (HMAC.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HMAC);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PacketProto other) {
      if (other == null) {
        return;
      }
      if (other.Opcode != global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode.Register) {
        Opcode = other.Opcode;
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.HMAC.Length != 0) {
        HMAC = other.HMAC;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Opcode = (global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode) input.ReadEnum();
            break;
          }
          case 18: {
            Timestamp = input.ReadString();
            break;
          }
          case 26: {
            Payload = input.ReadString();
            break;
          }
          case 34: {
            HMAC = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Opcode = (global::Google.Protobuf.CrapCord.PacketToProto.PacketProto.Types.PacketOpcode) input.ReadEnum();
            break;
          }
          case 18: {
            Timestamp = input.ReadString();
            break;
          }
          case 26: {
            Payload = input.ReadString();
            break;
          }
          case 34: {
            HMAC = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PacketProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum PacketOpcode {
        [pbr::OriginalName("Register")] Register = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("ViewRooms")] ViewRooms = 2,
        [pbr::OriginalName("FetchMessages")] FetchMessages = 3,
        [pbr::OriginalName("SendMessage")] SendMessage = 4,
        [pbr::OriginalName("CreateRoom")] CreateRoom = 5,
        [pbr::OriginalName("JoinRoom")] JoinRoom = 6,
        [pbr::OriginalName("Response")] Response = 7,
        [pbr::OriginalName("KeyHandoff")] KeyHandoff = 8,
        [pbr::OriginalName("Auth")] Auth = 9,
        [pbr::OriginalName("Disconnect")] Disconnect = 255,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
